"""empty message

Revision ID: 4b57cb62e20e
Revises: 94f48ad816c9
Create Date: 2024-12-07 22:32:42.231375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b57cb62e20e'
down_revision = '94f48ad816c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=False),
    sa.Column('speciality', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch'),
    sa.UniqueConstraint('datetime')
    )
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('speciality', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='appointments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointments_pkey'),
    sa.UniqueConstraint('branch', name='appointments_branch_key'),
    sa.UniqueConstraint('datetime', name='appointments_datetime_key')
    )
    op.drop_table('appointment')
    # ### end Alembic commands ###
